disabled_rules:
  - line_length
  - todo
  - variable_name
  - force_try
  - function_parameter_count
  - force_cast
  - type_name

included:
  - Sources
  - Tests

trailing_comma:
  mandatory_comma: true
